####################################################   EUREKA   ####################################################
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka

####################################################   CORS   ####################################################
spring:
  cloud:
    gateway:
      globalCors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

      ####################################################   USER-API   ####################################################
      routes:
        - id: public-api
          uri: lb://USER-API
          predicates:
            - Path=/api/auth/**
          order: 3

        - id: private-admin-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user, /api/user/activate/**, /api/user/deactivate/**, /api/user/create-delivery/**
          filters:
            - name: JwtAuthAdmin
          order: 1

        - id: private-user-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtAuthUser
          order: 2

        ####################################################   COUPON-API   ####################################################
        - id: private-coupon-api
          uri: lb://COUPON-API
          predicates:
            - Path=/api/consumptions/**, /api/coupons/**
          filters:
            - name: JwtAuthAdmin

        ####################################################   ORDER-API   ####################################################
        - id: private-order-api
          uri: lb://ORDER-API
          predicates:
            - Path=/api/order/**
          filters:
            - name: JwtAuthCustomer

        ####################################################   SHIPPING-API   ####################################################
        - id: private-shipping-api-0
          uri: lb://SHIPPING-API
          predicates:
            - Path=/api/shipments, /api/shipments/process/**, /api/shipments/ship/**
          filters:
            - name: JwtAuthAdmin

        - id: private-shipping-api-1
          uri: lb://SHIPPING-API
          predicates:
            - Path=/api/shipments/track, /api/shipments/cancel/**
          filters:
            - name: JwtAuthCustomer

        - id: private-shipping-api-2
          uri: lb://SHIPPING-API
          predicates:
            - Path=/api/shipments/confirm-delivery, /api/shipments/list-delivery
          filters:
            - name: JwtAuthDelivery
        ####################################################   STORE-API   ####################################################
        - id: public-s-api-0
          uri: lb://STORE-API
          predicates:
            - Path=/api/stores/{storeId}/products, /api/stores
          order: 1

        - id: private-store-api-0
          uri: lb://STORE-API
          predicates:
            - Path=/api/stores/**
          filters:
            - name: JwtAuthAdmin
          order: 2
