server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka

####################################################   USER-API   ####################################################
spring:
  cloud:
    gateway:
      routes:
        - id: public-api
          uri: lb://USER-API
          predicates:
            - Path=/api/auth/**
          order: 3

        - id: private-admin-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user,/api/user/activate/**,/api/user/deactivate/**,/api/user/create-delivery/**
          filters:
            - name: JwtAuthAdmin
          order: 1

        - id: private-user-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtAuthUser
          order: 2

####################################################   COUPON-API   ####################################################

        - id: private-coupon-api
          uri: lb://COUPON-API
          predicates:
            - Path=/api/consumptions/**, api/coupons/**
          filters:
            - name: JwtAuthAdmin