server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: public-api
          uri: lb://USER-API
          predicates:
            - Path=/api/auth/**
          order: 3

        - id: private-admin-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user,/api/user/activate/**,/api/user/deactivate/**
          filters:
            - name: JwtAuthAdmin
          order: 1

        - id: private-user-api
          uri: lb://USER-API
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtAuthUser
          order: 2